"""
Waiver Flow — Tool Implementations (Person 4)
===============================================
These three tools are consumed by Agent 2 (Person 2) via Strands @tool decorators.
Do NOT change the function signatures without team consensus.

Each tool is also deployed as a standalone Lambda function (see lambdas/).
The ARNs are exported from WaiverStack so Person 2 can wire them into AgentCore.

Tools:
  1. start_waiver_workflow  — create DynamoDB record + start Step Functions execution
  2. update_waiver_state    — merge new info into the record, append history
  3. get_waiver_state       — reload full waiver context (called at start of every reply)
"""

import json
import logging
import os
from datetime import datetime, timezone
from typing import Any

import boto3
from botocore.exceptions import ClientError
from strands import tool

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# AWS clients
# ---------------------------------------------------------------------------

def _dynamodb():
    return boto3.resource("dynamodb", region_name=os.environ["AWS_REGION"])

def _sfn():
    return boto3.client("stepfunctions", region_name=os.environ["AWS_REGION"])

def _table():
    return _dynamodb().Table(os.environ.get("WAIVER_TABLE", "waivers"))

def _sfn_arn() -> str:
    return os.environ["SFN_ARN"]

def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


# ---------------------------------------------------------------------------
# Tool 1 — start_waiver_workflow
# ---------------------------------------------------------------------------

@tool
def start_waiver_workflow(
    waiver_id: str,
    email_from: str,
    department: str,
    waiver_type: str,
    collected_info: dict,
    missing_fields: list[str],
) -> str:
    """
    Creates the waiver record in DynamoDB and starts a Step Functions execution
    with waitForTaskToken.

    Returns the task_token string — Agent 2 must store this; it is needed
    to resume the workflow when the human approver submits their decision.

    Parameters
    ----------
    waiver_id      : Unique waiver identifier (generated by Agent 2).
    email_from     : Email address of the requestor.
    department     : Department the waiver belongs to.
    waiver_type    : E.g. "medical", "financial_hardship", "academic".
    collected_info : Map of field_name → value gathered so far from the email.
    missing_fields : Fields still required before the waiver can be evaluated.

    Returns
    -------
    str — The Step Functions task token. Empty string on failure.
    """
    now = _now()

    # ----------------------------------------------------------------
    # 1. Create DynamoDB record
    # ----------------------------------------------------------------
    item = {
        "waiver_id":          waiver_id,
        "message_id":         "",           # Set by ingestion Lambda (Person 1) if available
        "thread_message_ids": [],
        "email_from":         email_from,
        "department":         department,
        "waiver_type":        waiver_type,
        "status":             "pending_info" if missing_fields else "pending_approval",
        "collected_info":     collected_info,
        "missing_fields":     missing_fields,
        "criteria":           {},           # Populated later by Agent 2 via update_waiver_state
        "task_token":         None,         # Set once SFN execution starts
        "history": [
            {
                "timestamp": now,
                "event":     "waiver_created",
                "content":   f"Waiver created for {email_from} — type: {waiver_type}",
            }
        ],
        "created_at": now,
        "updated_at": now,
    }

    try:
        _table().put_item(
            Item=item,
            ConditionExpression="attribute_not_exists(waiver_id)",
        )
        logger.info("DynamoDB record created | waiver_id=%s", waiver_id)
    except ClientError as exc:
        if exc.response["Error"]["Code"] == "ConditionalCheckFailedException":
            logger.warning("Waiver %s already exists — skipping create", waiver_id)
        else:
            logger.error("DynamoDB put_item failed: %s", exc)
            return ""

    # ----------------------------------------------------------------
    # 2. Start Step Functions execution — the state machine will emit
    #    a task token once it reaches WaitForHumanApproval.
    #    We pass waiver metadata as input; the SFN definition stores
    #    the task token back into DynamoDB via a Lambda task.
    # ----------------------------------------------------------------
    sfn_input = {
        "waiver_id":   waiver_id,
        "email_from":  email_from,
        "waiver_type": waiver_type,
        "department":  department,
    }

    try:
        sfn_resp = _sfn().start_execution(
            stateMachineArn=_sfn_arn(),
            name=f"waiver-{waiver_id}",
            input=json.dumps(sfn_input),
        )
        execution_arn = sfn_resp["executionArn"]
        logger.info("SFN execution started | waiver_id=%s | arn=%s", waiver_id, execution_arn)
    except ClientError as exc:
        logger.error("SFN start_execution failed: %s", exc)
        return ""

    # ----------------------------------------------------------------
    # 3. The actual task token is emitted by the WaitForHumanApproval
    #    state inside the SFN definition (see waiver_stack.py).
    #    The StoreTaskToken Lambda writes it to DynamoDB and returns it
    #    so Agent 2 can store it locally as well.
    #
    #    For the synchronous tool contract we poll DynamoDB briefly
    #    to retrieve the token once the SFN state has started.
    # ----------------------------------------------------------------
    import time
    task_token = ""
    for attempt in range(10):          # up to ~5 seconds
        time.sleep(0.5)
        resp = _table().get_item(Key={"waiver_id": waiver_id})
        token = resp.get("Item", {}).get("task_token")
        if token:
            task_token = token
            break
        logger.debug("Waiting for task token | attempt=%d", attempt + 1)

    if not task_token:
        logger.warning("Task token not yet available after polling | waiver_id=%s", waiver_id)

    # Persist execution ARN
    _table().update_item(
        Key={"waiver_id": waiver_id},
        UpdateExpression=(
            "SET sfn_execution_arn = :arn, updated_at = :ts, "
            "history = list_append(history, :h)"
        ),
        ExpressionAttributeValues={
            ":arn": execution_arn,
            ":ts":  _now(),
            ":h": [{
                "timestamp": _now(),
                "event":     "sfn_execution_started",
                "content":   f"Step Functions execution started: {execution_arn}",
            }],
        },
    )

    return task_token


# ---------------------------------------------------------------------------
# Tool 2 — update_waiver_state
# ---------------------------------------------------------------------------

@tool
def update_waiver_state(
    waiver_id: str,
    new_info: dict,
    missing_fields: list[str],
) -> bool:
    """
    Updates the waiver record in DynamoDB with newly collected information
    from the latest reply email. Appends a history entry.

    Parameters
    ----------
    waiver_id      : Existing waiver identifier.
    new_info       : New field_name → value pairs gathered from the email.
    missing_fields : Updated list of fields still outstanding.

    Returns
    -------
    bool — True on success, False on failure.
    """
    now    = _now()
    table  = _table()

    # Fetch existing collected_info to merge
    try:
        resp           = table.get_item(Key={"waiver_id": waiver_id})
        item           = resp.get("Item", {})
        existing_info  = item.get("collected_info", {})
    except ClientError as exc:
        logger.error("get_item failed: %s", exc)
        return False

    merged_info = {**existing_info, **new_info}
    new_status  = "pending_info" if missing_fields else "pending_approval"

    history_entry = {
        "timestamp": now,
        "event":     "info_updated",
        "content": (
            f"Updated fields: {list(new_info.keys())}. "
            f"Still missing: {missing_fields or 'nothing'}."
        ),
    }

    try:
        table.update_item(
            Key={"waiver_id": waiver_id},
            UpdateExpression=(
                "SET collected_info = :ci, missing_fields = :mf, "
                "#st = :st, updated_at = :ts, "
                "history = list_append(if_not_exists(history, :empty), :h)"
            ),
            ExpressionAttributeNames={"#st": "status"},
            ExpressionAttributeValues={
                ":ci":    merged_info,
                ":mf":    missing_fields,
                ":st":    new_status,
                ":ts":    now,
                ":h":     [history_entry],
                ":empty": [],
            },
        )
        logger.info(
            "Waiver updated | waiver_id=%s | status=%s | missing=%s",
            waiver_id, new_status, missing_fields,
        )
        return True
    except ClientError as exc:
        logger.error("update_item failed: %s", exc)
        return False


# ---------------------------------------------------------------------------
# Tool 3 — get_waiver_state
# ---------------------------------------------------------------------------

@tool
def get_waiver_state(waiver_id: str) -> dict:
    """
    Returns the full current state of a waiver from DynamoDB.
    Called by Agent 2 at the start of every reply email to reload context.

    Parameters
    ----------
    waiver_id : Waiver identifier.

    Returns
    -------
    dict — Full DynamoDB item, or {"error": "..."} if not found.
    """
    try:
        resp = _table().get_item(Key={"waiver_id": waiver_id})
        item = resp.get("Item")
        if not item:
            logger.warning("Waiver not found | waiver_id=%s", waiver_id)
            return {"error": f"Waiver {waiver_id!r} not found"}
        return dict(item)
    except ClientError as exc:
        logger.error("get_item failed: %s", exc)
        return {"error": str(exc)}
